FROM openjdk:8
RUN  apt-get update && apt-get install netcat-openbsd && apt-get install curl
RUN mkdir -p /usr/local/configserver

ADD @project.build.finalName@.jar /usr/local/configserver/
ADD run.sh run.sh
RUN chmod +x run.sh
CMD ./run.sh
